# .travis.yml
sudo: required

language:
  - python

python:
  - "3.6"

services:
  - docker

#install:
#  - "pip3 install -r requirements.txt"
#
#script:
#  - "python manage.py test"

script:
  - docker build -t patcurry/aws-django-docker .
  - docker run patcurry/aws-django-docker ./manage.py test