# .travis.yml
sudo: required

language:
  - python

python:
  - "3.6"

services:
  - docker

script:
  - docker build -t patcurry/aws-django-docker .
  - docker run patcurry/aws-django-docker ./manage.py test

# now how do I deploy this?
deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key:
    secure: "$SECRETACCESSKEY"
  region: "eu-central-1"
  app: "django-docker-template"
  app: "django-docker-template-dev"
  bucket_name: "elasticbeanstalk-eu-central-1-707675293479"
  on:
    branch: master